import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "Admin User",
      email: "admin@shopnext.com",
      password: bcrypt.hashSync("admin123", 10),
      isAdmin: true,
    },
    {
      name: "John Doe",
      email: "john@example.com",
      password: bcrypt.hashSync("password123", 10),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Classic White T-Shirt",
      slug: "classic-white-tshirt",
      category: "T-Shirts",
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
      price: 29.99,
      brand: "StyleCo",
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
      description: "A comfortable everyday white t-shirt made from 100% premium cotton. Breathable, soft, and perfect for any casual occasion.",
    },
    {
      name: "Slim Fit Chinos",
      slug: "slim-fit-chinos",
      category: "Pants",
      image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500",
      price: 59.99,
      brand: "UrbanFit",
      rating: 4.2,
      numReviews: 8,
      countInStock: 15,
      description: "Modern slim-fit chinos that transition seamlessly from office to weekend. Made from stretch fabric for all-day comfort.",
    },
    {
      name: "Hooded Sweatshirt",
      slug: "hooded-sweatshirt",
      category: "Hoodies",
      image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=500",
      price: 49.99,
      brand: "CozyWear",
      rating: 4.7,
      numReviews: 25,
      countInStock: 10,
      description: "A cozy pullover hoodie made from soft fleece. Features a kangaroo pocket and adjustable drawstring for a perfect fit.",
    },
    {
      name: "Denim Jacket",
      slug: "denim-jacket",
      category: "Jackets",
      image: "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=500",
      price: 89.99,
      brand: "UrbanFit",
      rating: 4.6,
      numReviews: 18,
      countInStock: 8,
      description: "A timeless denim jacket with a classic cut. Features two chest pockets and button-up front. A wardrobe essential.",
    },
    {
      name: "Running Shoes",
      slug: "running-shoes",
      category: "Shoes",
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
      price: 119.99,
      brand: "SpeedX",
      rating: 4.8,
      numReviews: 42,
      countInStock: 25,
      description: "Lightweight performance running shoes with responsive cushioning and breathable mesh upper. Built for speed and comfort.",
    },
    {
      name: "Leather Belt",
      slug: "leather-belt",
      category: "Accessories",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
      price: 34.99,
      brand: "StyleCo",
      rating: 4.3,
      numReviews: 7,
      countInStock: 30,
      description: "A genuine leather belt with a classic silver buckle. Versatile enough for both casual and formal outfits.",
    },
    {
      name: "Polo Shirt",
      slug: "polo-shirt",
      category: "T-Shirts",
      image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500",
      price: 39.99,
      brand: "StyleCo",
      rating: 4.4,
      numReviews: 15,
      countInStock: 18,
      description: "A classic polo shirt made from breathable pique cotton. Features a two-button placket and ribbed collar. Smart casual done right.",
    },
    {
      name: "Canvas Backpack",
      slug: "canvas-backpack",
      category: "Accessories",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
      price: 69.99,
      brand: "PackPro",
      rating: 4.5,
      numReviews: 20,
      countInStock: 12,
      description: "A durable canvas backpack with multiple compartments and padded laptop sleeve. Perfect for work, travel, or everyday use.",
    },
  ],
}

export default data
