import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Krishna',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Prav',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Navy Blue Hoodie',
      slug: 'navy-blue-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie1.jpg',
      price: 899,
      brand: 'Campus Sutra',
      rating: 4.4,
      numReviews: 14,
      countInStock: 22,
      description: 'A warm navy hoodie with a kangaroo pocket. Great for evenings out or college days.',
      isFeatured: true,
      banner: '/images/banner_hoodies.jpg',
    },
    {
      name: 'Brick Red Hoodie',
      slug: 'brick-red-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie2.jpg',
      price: 849,
      brand: 'Campus Sutra',
      rating: 4.1,
      numReviews: 9,
      countInStock: 18,
      description: 'Bold brick red color, fleece-lined for extra warmth. Unisex fit.',
      isFeatured: true,
      banner: '/images/banner_hoodies.jpg',
    },
    {
      name: 'Forest Green Hoodie',
      slug: 'forest-green-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie3.jpg',
      price: 799,
      brand: 'Wildcraft',
      rating: 3.9,
      numReviews: 6,
      countInStock: 15,
      description: 'Earthy green tone, soft cotton blend. A campus favourite.',
      isFeatured: true,
      banner: '/images/banner_hoodies.jpg',
    },
    {
      name: 'Deep Purple Hoodie',
      slug: 'deep-purple-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie4.jpg',
      price: 950,
      brand: 'The Souled Store',
      rating: 4.6,
      numReviews: 21,
      countInStock: 10,
      description: 'Rich deep purple. Thick fabric, drawstring hood, ribbed cuffs.',
    },
    {
      name: 'Charcoal Joggers',
      slug: 'charcoal-joggers',
      category: 'Joggers',
      image: '/images/jogger1.jpg',
      price: 699,
      brand: 'Jockey',
      rating: 4.3,
      numReviews: 17,
      countInStock: 30,
      description: 'Classic charcoal grey joggers with elastic waistband and side pockets.',
      isFeatured: true,
      banner: '/images/banner_joggers.jpg',
    },
    {
      name: 'Steel Blue Joggers',
      slug: 'steel-blue-joggers',
      category: 'Joggers',
      image: '/images/jogger2.jpg',
      price: 749,
      brand: 'Jockey',
      rating: 3.8,
      numReviews: 8,
      countInStock: 20,
      description: 'Cool steel blue with tapered leg. Good for gym or casual wear.',
    },
    {
      name: 'Camel Brown Joggers',
      slug: 'camel-brown-joggers',
      category: 'Joggers',
      image: '/images/jogger3.jpg',
      price: 799,
      brand: 'H&M',
      rating: 4.0,
      numReviews: 11,
      countInStock: 14,
      description: 'Trendy camel tone. Slim fit with zippered ankle cuffs.',
    },
  ],
}

export default data
